#spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo
server:
  port: 9090
camunda:
  bpm:
    generic-properties:
      properties:
        userResourceWhitelistPattern: ".+"
    database:
      type: postgres
spring:
    jpa:
      database-platform: ${PLATFORM}
    datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: ${DB_DRIVER}
 # jpa:
 #   database-platform:
 #     org.hibernate.dialect.PostgreSQLDialect
 # datasource:
 #   url: jdbc:postgresql://localhost:5432/kafka
#  username: postgres
 #   password: demo
 #   driver-class-name:  org.postgresql.Driver