

spring:
  main:
    web-application-type: reactive
  application:
    name: client-eureka
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true