version: "3"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: 1
    ports:
      - "2181:2181"
    networks:
      - app-tier
    container_name: zookeeper

  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    container_name: kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 1
    ports:
      - "9092:9092"
    networks:
      - app-tier

  internalapplication:
    image: internalapplication:v1.0
    ports:
      - 9090:9090
    container_name: internalapplication
    networks:
      - app-tier

  externalapplication:
    image: externalapplication:v1.0
    ports:
      - 7070:7070
    container_name: externalapplication
    networks:
      - app-tier