spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo



spring:
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url:  jdbc:postgresql://localhost:5432/kafka
    username: postgres
    password: demo
    driver-class-name:  org.postgresql.Driver

server:
  port: 8081