spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo

camunda:
  bpm:
    generic-properties:
      properties:
        userResourceWhitelistPattern: ".+"
    database:
      type: postgres

spring:
  jpa:
    database-platform: ${PLATFORM}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
server:
  port: 8081
